### PR TITLE
Updated Colors & Updated Slides with Images & Gif

### PR DESCRIPTION
**Pull request by ryanbrownhill**
I updated the colors based off #6 And added some images / gifs that I feel might fit. Alignment of elements needs to be refined.

### CODE REVIEW

**Comment by ryanbrownhill** [comment]
Need to update my files with the new my Sass architecture & create a new pull request.

**Comment by una** [comment]
love it :smile:

**Comment by una** [comment]
Ooh was there a merge conflict because of the pull?

**Comment by una** [comment]
if you need help merging this, lmk

**Comment by ryanbrownhill** [comment]
@una  
So I just saw your comment.... But I figured out a work around for it. What I did:
- Cloned your repo to a new file
- Added my changes that I had for the appropriate SCSS files.
- Had a Error with Gulp for forever...
- Realized the error was its because I changed ALL the $purple variables to $teal and that changed something in shower that was causing the error.
- So I cloned the repo again and was very careful with the changes for the $purples to $teal.
- Then I couldn't add my changes to my old branch
- So I created a new branch "ryan"
- Now I have a real pull request #15 with the correct changes.
- YAYY :tada::tada::tada::tada::tada::tada:

**Pull request closed without merging**
